### ISSUE TITLE
PE-HAI collaboration paradigm related

### ISSUE THREAD

**Issue by Daihefeng** [zilin-huang/PE-RLHF#2]
I've successfully replicated the baseline training phases for each algorithm. I'm curious about the PE-HAI collaboration paradigm you mentioned in your paper, particularly the formula in Chapter 4. Is there a specific part of the GitHub open-source code that corresponds to it? There’s quite a bit of code, and I haven’t had a chance to look through it all, so I’d appreciate your guidance!

**Comment by zilin-huang** [comment]
Hi, you can look into ```lines 184-231``` in ```PE-RLHF/pe_rlhf/utils/pe_rlhf_human_in_the_loop_env.py```. The ```value_based_takeover_method``` function implements key logic for the PE-HAI collaboration mechanism.

**Comment by Daihefeng** [comment]
Thank you for your response!
